Refactor avahi and bluez instructions
canonical/matter-docs pull request #30
Opened 2024-06-26 09:04 UTC by farshidtz

Related issues:
- Close #24
- Close #26

2024-06-26 09:24 UTC, farshidtz commented
@jpm-canonical to serve locally:
```
make run
```
and hope that there are no dependency issues.

2024-06-27 11:10 UTC, jpm-canonical requested changes

2024-06-27 11:10 UTC, jpm-canonical commented on how-to/chip-tool-commission-and-control.rst
> +The snap restricts the app's access to necessary resources on the host.
```suggestion
The snap restricts the app's access to only the necessary resources on the host.
```

2024-06-27 11:10 UTC, jpm-canonical commented on how-to/chip-tool-commission-and-control.rst
> +The access to host is managed via `snap interface <https://snapcraft.io/docs/interface-management>`_ connections.
```suggestion
This access can be managed via `snap interface <https://snapcraft.io/docs/interface-management>`_ connections.
```

2024-06-27 11:10 UTC, jpm-canonical commented on how-to/chip-tool-commission-and-control.rst
> +By default, the snap auto connects the following interfaces:
```suggestion
By default the snap auto connects the following interfaces:
```

2024-06-27 11:15 UTC, jpm-canonical commented
A general remark I have about this set of how-to's on matter is that there is a lot of duplication. Especially when it comes to chip-tool. It's definitely not something to address now, but something to think about.

2024-06-28 09:11 UTC, farshidtz commented on how-to/chip-tool-commission-and-control.rst
> +By default, the snap auto connects the following interfaces:
"By default" is an introductory phrase, which is usually followed by a comma to improve readability. I did some research and this appears to be common practice.

2024-06-28 10:50 UTC, jpm-canonical approved these changes

2024-06-28 10:51 UTC, merged