Extend explanations on available releases
canonical/matter-docs pull request #31
Opened 2024-06-26 09:20 UTC by farshidtz

2024-06-27 10:48 UTC, jpm-canonical requested changes
In my opinion these changes do not make the documentation more user friendly. In fact we are only providing half of the info (list available versions), while the other half of the info (installing another version) needs to be found in the linked documentation.

I would say we remove these paragraphs about other versions completely to make it easier for a new user to understand. Then we can add a new page or paragraph at the end about pre-release versions, discussing: 
* what they are
* how to interpret their version numbers 
* how to install them

That way power users can find the info, but we don't complicate the main flow of the docs for newcomers.

2024-06-27 10:48 UTC, jpm-canonical commented on tutorial/pi-gpio-commander.md
> +
This whole paragraph feels a little out of place here. It interrupts the flow of the guide. Maybe simplify it to just a note, as the document we link to already describes what channels are and how to list available versions.

> Pre-release versions of matter-pi-gpio-commander is available in different [channels](https://snapcraft.io/docs/channels).

2024-06-27 10:48 UTC, jpm-canonical commented on how-to/chip-tool-commission-and-control.rst
> +Check the available releases from the store page or with: ``snap info chip-tool``
The docs on snapcraft channels already describe how to list available releases and how to install them. I'm not sure adding the list command here makes it clearer, as the second step of installing it is still missing. Maybe better to leave the paragraph as is, or omitting it completely.

2024-06-28 09:28 UTC, farshidtz commented
I agree with the comments. Could add a new explanation doc in the future, but I don't see that necessary right now.

2024-06-28 09:29 UTC, jpm-canonical approved these changes
Yes this is nicer for now

2024-06-28 09:29 UTC, merged